"""initial schema

Revision ID: ed5916ce4755
Revises: 
Create Date: 2026-05-24 10:29:07.892666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed5916ce4755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_rooms', sa.Integer(), nullable=True),
    sa.Column('max_rooms', sa.Integer(), nullable=True),
    sa.Column('min_sqm', sa.Integer(), nullable=True),
    sa.Column('max_sqm', sa.Integer(), nullable=True),
    sa.Column('temporal', sa.String(length=10), nullable=False),
    sa.Column('ocupada', sa.String(length=10), nullable=False),
    sa.Column('alquiler_regulado', sa.String(length=10), nullable=False),
    sa.Column('nuda_propiedad', sa.String(length=10), nullable=False),
    sa.Column('elevator', sa.String(length=5), nullable=False),
    sa.Column('furnished', sa.String(length=5), nullable=False),
    sa.Column('garage', sa.String(length=5), nullable=False),
    sa.Column('terrace', sa.String(length=5), nullable=False),
    sa.Column('balcony', sa.String(length=5), nullable=False),
    sa.Column('pets_allowed', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('square_meters', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('is_agency', sa.Boolean(), nullable=True),
    sa.Column('publisher_name', sa.String(length=200), nullable=True),
    sa.Column('photos_amount', sa.Integer(), nullable=True),
    sa.Column('flag_temporal', sa.Boolean(), nullable=False),
    sa.Column('flag_ocupada', sa.Boolean(), nullable=False),
    sa.Column('flag_alquiler_regulado', sa.Boolean(), nullable=False),
    sa.Column('flag_bare_ownership', sa.Boolean(), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_property_id'), 'listings', ['property_id'], unique=True)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('listings_fetched', sa.Integer(), nullable=False),
    sa.Column('new_listings', sa.Integer(), nullable=False),
    sa.Column('matches_found', sa.Integer(), nullable=False),
    sa.Column('alerts_sent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_id', 'listing_id', name='uq_filter_listing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('settings')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_listings_property_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('filters')
    # ### end Alembic commands ###
